[project]
name = "cfd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipympl>=0.9.8",
    "ipython>=9.8.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "napari[pyqt6]>=0.6.6",
    "tqdm>=4.67.1",
]
